### ISSUE TITLE
[Feature Request] move specific files into the top-level

### ISSUE THREAD

**Issue by GTrunSec** [divnix/incl#2]
In order to make the paths of cellsFrom more structured, we can filter the files of specified subdirectories to the root directory. especially,  for the hive users who want to migrate from digga to hive.

Action expected:
```nix
   cellsFrom =  std.incl ./. [
      (std.incl.moveRoot ./users)
      (std.incl.moveRoot ./hosts)
      ./lib
     ];
```

- the sources will be:
```
sources: 
  - <cell1> from users/cells/<1, 2, 3>
  - <cell2> from hostsDir/cells<1, 2.3>
  - <cell3>  from the libDir of cells
```

**Comment by blaggacao** [comment]
Did you probably mean: `(std.incl.moveRoot ./sub/folder/users)` ?

Since that's not really a `incl` concern, nor a `std` concern, I would almost advise to implement this inside of `hive`, wdyt?

Otherwise I see and acknowledge the use case (this is part of the legitimate history of `hive`):

> especially, for the hive users who want to migrate from digga to hive

**Comment by GTrunSec** [comment]
> Did you probably mean: (std.incl.moveRoot ./sub/folder/users) ?

exactly.

> Since that's not really a incl concern, nor a std concern

thanks for your reminder. 

>  I would almost advise to implement this inside of hive, wdyt?

Agreed, it would be a more appropriate place to implement that.
